---
root: true

env:
  node: true
  es6: true

settings:
  ecmascript: 6

parser:
  "babel-eslint"

extends:
  - google

rules:
  no-console: 0
  object-curly-spacing:
    - error
    - always
  no-invalid-this: 0
